server:
  port: 8000

logging:
  level:
    pl:
      kukla:
        krzys: debug

spring:
  application:
    name: 04-currency-exchange-service
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      # it allows to register this microservice to eureka naming server
      defaultZone: http://localhost:8761/eureka

